# Списки, кортежи, множества, словари

# Оглавление

* [Списки](#lists)
* [List comprehensions](#lists_comprehensions)
* [Кортежи (Tuples)](#tuples)
* [Множества (Sets)](#sets)
* [Frozen sets](#frozen_sets)
* [Словари (Dictionaries)](#dictionaries)

## Списки <a class="anchor" id="lists"></a>

Списки имеют различные методы для работы с ними:
    
list.append(x) - добавляет элемент x в конец списка. То же самое, что и **a[len(a):] = [x]**

list.extend(iterable) - расширяет список добавляя в конец все объекты итерируемой переменной **iterable**. 
То же самое, что и **a[len(a):] = iterable**.

list.insert(i, x) - помещает элемент **x** на указанную позицию **i**

list.remove(x) - удаляет первый элемент со значением x из списка. 
Если элемета с таким значение нет, будет вызвана ошибка

list.pop([i]) - удаляет элемент в позиции **i** и возвращает его. 
Если индекс **i** не указан, берется последний элемент. Квадратные скобки означают, что параметр является опциональным

list.clear() - удаляет все элементы списка. То же самое, что и **del a[:]**

list.index(x[, start[, end]]) - возвращает индекс первого в списке элемента **x**. 
Если элемента нет, то вызывается ошибка. Опциональные параметры позволяют сократить область поиска элемента, 
однако индекс полученного элемента будет считаться по всему списку, а не по выборке ограниченной опциональными переменными

list.count(x) - возвращает количество элемента **x** в списке

list.sort(key=None, reverse=False) - сортирует список

list.reverse() - переворачивает список

list.copy() - возвращает копию списка. То же самое, что и **a[:]**

Несколько примеров по приведенным выше методам:

In [33]:
fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']
print('#1 ', fruits.count('apple'))

print('#2 ', fruits.count('tangerine'))

print('#3 ', fruits.index('banana'))

print('#4 ', fruits.index('banana', 4)) # Начинаем поиск с 4ой позиции

fruits.reverse()
print('#5 ', fruits)

fruits.append('grape')
print('#6 ', fruits)

fruits.sort()
print('#7 ', fruits)

print('#8 ', fruits.pop())

#1  2
#2  0
#3  3
#4  6
#5  ['banana', 'apple', 'kiwi', 'banana', 'pear', 'apple', 'orange']
#6  ['banana', 'apple', 'kiwi', 'banana', 'pear', 'apple', 'orange', 'grape']
#7  ['apple', 'apple', 'banana', 'banana', 'grape', 'kiwi', 'orange', 'pear']
#8  pear


Стоит обратить внимание на то, что методы **insert, remove, sort** изменяют список и возвращают пустое значение None

Списки можно использовать как стэки (последний пришел, первый ушел) просто применяя методы **append()** и **pop()**

In [30]:
stack = [3, 4, 5]
stack.append(6)
stack.append(7)
print('#1 ', stack)

print('#2 ', stack.pop())

print('#3 ', stack)

print('#4 ', stack.pop())

print('#5 ', stack.pop())

print('#6 ', stack)

#1  [3, 4, 5, 6, 7]
#2  7
#3  [3, 4, 5, 6]
#4  6
#5  5
#6  [3, 4]


Также списки можно использовать для реализации очередей (первый пришел, первый ушел). Однако реализация очередей через списки будет неэффективна. Если добавление в конец и удаление с конца списка юудут работать быстро, то вставка элемента в начало списка и удаление элемента из начала списка будет работать медленнее, так как нам придется сдвигать элементы на 1 
Для реализации оереди лучше использовать **collections.deque**, разработанный специально для быстрой вставки и удаления элементов с обоих концов

In [35]:
from collections import deque
queue = deque(["Eric", "John", "Michael"])
queue.append("Terry")
print('#1 ', queue)
queue.append("Graham")
print('#2 ', queue)
print('#3 ', queue.popleft())
print('#4 ', queue.popleft())
print('#5 ', queue)

#1  deque(['Eric', 'John', 'Michael', 'Terry'])
#2  deque(['Eric', 'John', 'Michael', 'Terry', 'Graham'])
#3  Eric
#4  John
#5  deque(['Michael', 'Terry', 'Graham'])


## List comprehensions  <a class="anchor" id="lists_comprehensions"></a>

List comprehensions обеспечивает краткий способ создания списков. 
Обычным применением list comprehansion является создание новых списков, где каждый элемент списка является результатом некоторых операций, применяемых к каждому элементу, или создание подпоследовательности тех элементов, которые удовлетворяют определенному условию.

Например, предположим, что мы хотим создать список из элементов возведенных в квадрат:

In [9]:
squares = []
for x in range(10):
    squares.append(x**2)

squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

Обратите внимание, что данные действия создают (или перезаписывают) переменную **x**, которая все еще существует после завершения цикла. 
Мы можем вычислить список квадратов без каких-либо побочных эффектов, используя:

In [10]:
squares = list(map(lambda x: x**2, range(10)))
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

или 

In [11]:
squares = [x**2 for x in range(10)]
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

List comprehension состоит из скобок, содержащих выражение, за которым следует цикл **for**, а затем либо не следует ничего либо другие циклы **for** или условия **if**. 
Результатом будет новый список, полученный в результате выполнения всех выражений заключенных в скобки. Например, этот list comprehensions объединяет элементы двух списков, если они не равны:

In [40]:
[(x, y) for x in [1,2,3] for y in [3,1,4] if x != y]

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]

Это то же самое, что и 

In [41]:
combs = []
for x in [1,2,3]:
    for y in [3,1,4]:
        if x != y:
            combs.append((x, y))

combs

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]

Заметьте, что порядок **for** и **if** в обоих случаях одинаков

Рассмотрим еще несколько примеров

In [43]:
vec = [-4, -2, 0, 2, 4]
# создание нового списка, где все значения умножены на 2
[x*2 for x in vec]

[-8, -4, 0, 4, 8]

In [44]:
# исклчючаем все отрицательные значения
[x for x in vec if x >= 0]

[0, 2, 4]

In [45]:
# применяем функцию abs() ко все элементам списка
[abs(x) for x in vec]

[4, 2, 0, 2, 4]

In [46]:
# вызываем метод strip() для каждой строки
freshfruit = ['  banana', '  loganberry ', 'passion fruit  ']
[weapon.strip() for weapon in freshfruit]

['banana', 'loganberry', 'passion fruit']

In [50]:
# создаем список кортежей вида (число, квадрат числа)
[(x, x**2) for x in range(6)]

[(0, 0), (1, 1), (2, 4), (3, 9), (4, 16), (5, 25)]

In [51]:
# обратим внимание, что возвращаемое значение это единственный объект. Если неободимо вернуть несколько значений, то нужно обернуть их, например, в кортеж 
[x, x**2 for x in range(6)]

SyntaxError: invalid syntax (<ipython-input-51-4ff55b8c241c>, line 2)

In [53]:
# работа с вложенным списком и преобразование его в обычный список
vec = [[1,2,3], [4,5,6], [7,8,9]]
[num for elem in vec for num in elem]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

Выражения в list comprehension могут включать себя другие list comprehension, например:

In [12]:
# возьмем матрицу 3х4
matrix = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
]

Следующим list comprehension мы можем транспонировать матрицу

In [13]:
[[row[i] for row in matrix] for i in range(4)]

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

Данный пример эквивалентен:

In [14]:
transposed = []
for i in range(4):
    transposed.append([row[i] for row in matrix])

transposed

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

Что в свою очередь является тем же самым, что и

In [58]:
transposed = []
for i in range(4):
    transposed_row = []
    for row in matrix:
        transposed_row.append(row[i])
    transposed.append(transposed_row)

transposed

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

Хотя на самом деле в реальном мире наверное стоит воспользоваться встроенной функцией zip() для данной задачи

In [61]:
list(zip(*matrix))

[(1, 5, 9), (2, 6, 10), (3, 7, 11), (4, 8, 12)]

Есть способ удалить элемент из списка по индексу, а не только по значению. Его отличие от метода pop() заключается в том, что del позволяет делать удаление еще и по срезам или очистку всего списка

In [63]:
a = [-1, 1, 66.25, 333, 333, 1234.5]
del a[0]
a

[1, 66.25, 333, 333, 1234.5]

In [64]:
del a[2:4]
a

[1, 66.25, 1234.5]

In [65]:
del a[:]
a

[]

Также дел может использоваться для удаление переменной

In [66]:
del a

## Кортежи (Tuples) <a class="anchor" id="tuples"></a>

Кроме списка существует также другой стандартный тип данных: кортеж.

Кортеж состоит из ряда значений, разделенных запятыми, например: 

In [2]:
t = 12345, 54321, 'hello!'
t[0]

12345

In [3]:
t

(12345, 54321, 'hello!')

In [10]:
t = (12345, 54321, 'hello!')
t[0]

12345

In [13]:
t

(12345, 54321, 'hello!')

In [7]:
# Кортежи могут быть вложенными
u = t, (1, 2, 3, 4, 5)
u

((12345, 54321, 'hello!'), (1, 2, 3, 4, 5))

In [5]:
# Кортеж как и строка является неизменяемым объектом
t[0] = 88888

TypeError: 'tuple' object does not support item assignment

In [8]:
# При этом кортежи могут содержать изменяемые объекты
v = ([1, 2, 3], [3, 2, 1])
v

([1, 2, 3], [3, 2, 1])

- Кортежи могут быть заключены в круглые скобки, а могут задаваться и без скобок 
- Невозможно назначить отдельные элементы кортежа, однако можно создавать кортежи, содержащие изменяемые объекты, такие как списки.

Пустые кортежи состоят из пары пустых скобок; 
Кортеж с одним элементом создается следующим образом. Например: 

In [17]:
empty = ()
singleton = 'hello',    # <-- обратите внимение на запятую
len(empty)

0

In [18]:
len(singleton)

1

In [19]:
singleton

('hello',)

Вспомним выражение **t = 12345, 54321, 'hello!'**. Это пример упаковки кортежа: значения **12345**, **54321** и **hello!** упакованы в кортеж. Возможна и обратная операция: 

In [21]:
x, y, z = t

In [23]:
x

12345

In [24]:
y

54321

In [25]:
t

(12345, 54321, 'hello!')

Это называется распаковкой последовательности (sequence unpacking) и работает для любой последовательности с правой стороны. 
Для распаковки последовательности требуется, чтобы слева от знака равенства было столько переменных, сколько элементов в последовательности.

## Множества (Sets) <a class="anchor" id="sets"></a>

Python также включает тип данных для множеств. Множество - это неупорядоченная коллекция без повторяющихся элементов. Множества поддерживают математические операции, такие как объединение, пересечение, разность и симметрическая разность.

Фигурные скобки или функцию set () можно использовать для создания множест. Примечание: чтобы создать пустое множество, вы должны использовать set (), а не {}; последний создает пустой словарь - структуру данных, которую мы обсудим в далее. 

In [32]:
basket = {'apple', 'orange', 'apple', 'pear', 'orange', 'banana'}
print(basket)                      # show that duplicates have been removed

{'apple', 'banana', 'orange', 'pear'}


In [33]:
'orange' in basket                 # fast membership testing

True

In [34]:
'crabgrass' in basket

False

In [36]:
a = set('abracadabra')
b = set('alacazam')
a                                  # в а остались только уникальные элементы

{'a', 'b', 'c', 'd', 'r'}

In [37]:
a - b                              # символы содержащиеся в а, которых нет в b

{'b', 'd', 'r'}

In [38]:
a | b                              # символы содержащиеся в а или в b, или и там и там

{'a', 'b', 'c', 'd', 'l', 'm', 'r', 'z'}

In [39]:
a & b                              # символы содержащиеся в обоих множествах

{'a', 'c'}

In [40]:
a ^ b                              # символы содержащиеся только в а или только в, но не в обоих

{'b', 'd', 'l', 'm', 'r', 'z'}

Для множеств может быть применен схожий с list comprehansion синтаксис

In [41]:
a = {x for x in 'abracadabra' if x not in 'abc'}
a

{'d', 'r'}

In [ ]:
set()

## Frozen sets <a class="anchor" id="frozen_sets"></a>

Единственное отличие set от frozenset заключается в том, что set - изменяемый тип данных, а frozenset - нет. 

In [27]:
a = set('qwerty')
b = frozenset('qwerty')
a == b

True

In [28]:
type(a - b)

set

In [29]:
type(a | b)

set

In [30]:
a.add(1)

In [31]:
a

{1, 'e', 'q', 'r', 't', 'w', 'y'}

In [32]:
b.add(1)

AttributeError: 'frozenset' object has no attribute 'add'

## Словари (Dictionaries) <a class="anchor" id="dictionaries"></a>

Другой полезный тип данных, встроенный в Python, - это словарь. 
В отличие от последовательностей, которые индексируются диапазоном чисел, словари индексируются ключами, которые могут быть любого неизменяемого типа; 
Кортежи можно использовать в качестве ключей, если они содержат только строки, числа или кортежи; 
если кортеж прямо или косвенно содержит какой-либо изменяемый объект, его нельзя использовать в качестве ключа. 
Вы не можете использовать списки в качестве ключей, поскольку списки можно изменять.

Лучше всего рассматривать словарь как неупорядоченный набор пар ключ: значение с требованием, чтобы ключи были уникальными (в пределах одного словаря). 
Пара фигурных скобок создает пустой словарь: {}. Поместив разделенные запятыми пары ключ: значение в фигурные скобки можно добавть в 
словарь начальные пары ключ: значение; так же словари записываются и при выводе.

Основные операции со словарем - это сохранение значения с некоторым ключом и извлечение значения с данным ключом. 
Также можно удалить пару ключ: значение с помощью del. Если вы сохраняете новое значение, используя ключ, который уже используется, старое значение, 
связанное с этим ключом, забывается. 
Извлечение значения с использованием несуществующего ключа вызывает ошибку.

Выполнение list (d.keys ()) в словаре возвращает список всех ключей, используемых в словаре, в произвольном порядке (если вы хотите его отсортировать, просто используйте вместо этого sorted (d.keys ())). 
Чтобы проверить, есть ли в словаре единственный ключ, используйте ключевое слово in.

Вот небольшой пример использования словаря: 

In [46]:
tel = {'jack': 4098, 'sape': 4139}
tel['guido'] = 4127
tel

{'jack': 4098, 'sape': 4139, 'guido': 4127}

In [47]:
tel['jack']

4098

In [48]:
del tel['sape']
tel['irv'] = 4127
tel

{'jack': 4098, 'guido': 4127, 'irv': 4127}

In [49]:
list(tel.keys())

['jack', 'guido', 'irv']

In [50]:
sorted(tel.keys())

['guido', 'irv', 'jack']

In [51]:
'guido' in tel

True

In [52]:
'jack' not in tel

False

Словари содержат следующие методы:

get(key[, default])
Возвращает значение ключа, если ключ находится в словаре, иначе возвращает значение **default**. 
Если значение по умолчанию не указано, по умолчанию используется значение **None**, поэтому этот метод никогда не вызывает ошибку KeyError.

items()
Возвращает новое представление элементов словаря (пары (ключ, значение)).

keys()
Возвращает новое представление ключей словаря.

pop(key[, default])
Если ключ находится в словаре, удаляет его и возвращает его значение, иначе возвращает значение по умолчанию.
Если значение по умолчанию не указано и ключ отсутствует в словаре, возникает ошибка KeyError.

popitem ()
Удаляет и возвращает произвольную пару (ключ, значение) из словаря.
popitem () полезен для деструктивного перебора словаря, что часто используется в алгоритмах набора. Если словарь пуст, вызов popitem () вызывает KeyError.

setdefault(key[, default])¶
Если ключ находится в словаре, возвращает его значение. 
Если нет, вставляет ключ со значением по умолчанию и возвращает значение по умолчанию.

update([other])
Обновляет словарь парами ключ / значение из **other**, перезаписав существующие ключи. Ничего не возвращает.
update () принимает либо другой словарь, либо итерируемы переменные пар ключ / значение (как кортежи или другие объекты длины два).

values()
Возвращает значения словаря.

Еще немного примеров:

In [65]:
dict([('sape', 4139), ('guido', 4127), ('jack', 4098)])

{'sape': 4139, 'guido': 4127, 'jack': 4098}

In [66]:
{x: x**2 for x in (2, 4, 6)}

{2: 4, 4: 16, 6: 36}

In [67]:
dict(sape=4139, guido=4127, jack=4098)

{'sape': 4139, 'guido': 4127, 'jack': 4098}

In [1]:
knights = {'gallahad': 'the pure', 'robin': 'the brave'}
for k, v in knights.items():
    print(k, v)

gallahad the pure
robin the brave


In [69]:
for i, v in enumerate(['tic', 'tac', 'toe']):
    print(i, v)

0 tic
1 tac
2 toe


In [73]:
questions = ['name', 'quest', 'favorite color']
answers = ['lancelot', 'the holy grail', 'blue']
for q, a in zip(questions, answers):
    print('What is your {0}?  It is {1}.'.format(q, a))

What is your name?  It is lancelot.
What is your quest?  It is the holy grail.
What is your favorite color?  It is blue.


In [75]:
for i in reversed(range(1, 10, 2)):
    print(i)

9
7
5
3
1


In [80]:
for i in range(9, 0, -2):
    print(i)

9
7
5
3
1


In [81]:
basket = ['apple', 'orange', 'apple', 'pear', 'orange', 'banana']
for f in sorted(set(basket)):
    print(f)

apple
banana
orange
pear


Объекты последовательности можно сравнивать с другими объектами того же типа последовательности. 
При сравнении используется лексикографический порядок: сначала сравниваются первые два элемента, и если они различаются, это определяет результат сравнения; 
если они равны, сравниваются следующие два элемента и так далее, пока не будет исчерпана любая последовательность. 
Если два сравниваемых элемента сами являются последовательностями одного типа, лексикографическое сравнение выполняется рекурсивно. 
Если все элементы двух последовательностей сравниваются равными, последовательности считаются равными.
Если одна последовательность является начальной подпоследовательностью другой, более короткая последовательность является меньшей (меньшей).
Некоторые примеры сравнений однотипных последовательностей: 

In [ ]:
(1, 2, 3)              < (1, 2, 4)
[1, 2, 3]              < [1, 2, 4]
'ABC' < 'C' < 'Pascal' < 'Python'
(1, 2, 3, 4)           < (1, 2, 4)
(1, 2)                 < (1, 2, -1)
(1, 2, 3)             == (1.0, 2.0, 3.0)
(1, 2, ('aa', 'ab'))   < (1, 2, ('abc', 'a'), 4)